### ISSUE TITLE
[api] Increase version to uint32

### ISSUE THREAD

**Issue by thraneh** [mmitkevich/roq-rencap#40]
Pros

* Required by RenCap's market-making strategies

Cons

* Roq's order ID generator will increase it's requirement from 15 bytes (binary) / 20 characters (base64) to 18 bytes (binary) / 24 characters (base64)
* BitMEX allows 36 characters for ClOrdID, that leaves only 12 characters we can append for the Tbricks ClOrdID

Note! Roq generates a unique order id using

* request version (now 4 bytes)
* user's id (1 byte)
* user's order id (4 bytes)
* timestamp in nanoseconds (8 bytes)
* checksum (1 byte)

**Comment by thraneh** [comment]
Was implemented early this week

**Comment by mmitkevich** [comment]
closing - had no problems yet
